language: php

php:
  - 5.5
  - 5.6
  - hhvm
  
env:
  - LARAVEL_VERSION="5.0.*"
  - LARAVEL_VERSION="5.1.*"
  - LARAVEL_VERSION="5.2.*"

install:
  - composer self-update
  - composer require laravel/framework:${LARAVEL_VERSION} --no-update --no-interaction
  - composer install --prefer-source --no-interaction
  
before_script:
  - composer dump-autoload -o

script:
  - vendor/bin/phpspec run
  - vendor/bin/phpunit
  - php CoverageChecker.php clover.xml 65
